### PR TITLE
default option.

### PR DESCRIPTION
**Pull request by datnordstrom**

### CODE REVIEW

**Comment by yowainwright** [comment]
@datnordstrom I believe that would error. Could we follow up in the issue? I will help you there.

**Review by yowainwright — CHANGES_REQUESTED** [review]
I am not 100% but _I think_ that would error because the variable `dir` would not be assigned a value. Also, I think we were getting somewhere in the issue that was submitted.

**Comment by datnordstrom** [comment]
yes it does....

**Comment by datnordstrom** [comment]
Actually I modified it on my /dist/ and it works. even makes my #33 issue resolved..

**Comment by yowainwright** [comment]
@datnordstrom okay, could we discuss what I'm pointing out in the issue itself? 

----

It looks like the code that was changed wasn't compiled **to** `dist`. It looks like it was changed **in** `dist` directly which presents a problem that shouldn't be approached within this PR that won't be merged.  For furture reference, check out the [npm scripts](https://docs.npmjs.com/misc/scripts). In order to build correctly, with a shell, the developer will have to `npm i && npm run build`.

**Pull request closed without merging**
